from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field
from app.services.chat_engine import get_chatbot_response

router = APIRouter()

class ChatRequest(BaseModel):
    session_id: str = Field(
        ..., 
        description="Unique session token tracking the conversational state in Redis",
        example="student_session_idx_101"
    )
    message: str = Field(
        ..., 
        description="The natural language question sent by the student user",
        example="What are the core components of an LLM agent?"
    )

class ChatResponse(BaseModel):
    status: str = Field(default="success", example="success")
    reply: str = Field(..., description="The context-aware response generated by Gemini")

@router.post("/chat", response_model=ChatResponse)
async def interact_with_assistant(data: ChatRequest):
    """
    POST Gateway for the Nexus AI Chatbot Assistant.
    Coordinates real-time context retrieval across events and documentation 
    while preserving interaction history using an active Redis cache cluster.
    """
    try:
        # Pass payload items cleanly to your modern service handler
        reply = get_chatbot_response(session_id=data.session_id, user_message=data.message)
        
        return ChatResponse(
            status="success",
            reply=reply
        )
        
    except Exception as e:
        # Gracefully handle missing Redis connections or API keys
        raise HTTPException(
            status_code=500, 
            detail=f"Nexus AI Chatbot Engine Fault: {str(e)}"
        )